spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: carrinho-service
          uri: lb://carrinho-service
          predicates:
            - Path=/carrinho/**
          filters:
            - StripPrefix=1
        - id: pedido-service
          uri: lb://pedido-service
          predicates:
            - Path=/pedido/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
        - id: produto-service
          uri: lb://produto-service
          predicates:
            - Path=/produto/**
          filters:
            - StripPrefix=1

server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/